DELETE  http://localhost:8080/events/2/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbGwiOiJ0ZXN0MUB0ZXN0LmNvbSIsImV4cCI6MTczNzI2MTI5NywidXNlcklEIjozfQ.B3C5WNp0TTkNip-QLX75Jemw_e2L9c3I6ibMRW9Bz3E
