PUT http://localhost:8080/events/1
content-type:application/json
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbGwiOiJsb3FlYkBtYWlsaW5hdG9yLmNvbSIsImV4cCI6MTczNzM0ODIzMywidXNlcklEIjo5fQ.sbskshoD5LK78By5wM-brmMsdX7VvG3r-ghZMBMwlHw

{
    "name": "updated",
    "price": 1231231231,
    "Description": "50% maghz",
    "dateTime": "2025-01-01T15:30:00Z"
}
